version: "3"

networks:
  redis_network:
    driver: overlay
    external: false

services:
  redis:
    image: redister:dev
    command: node index.js
    working_dir: /opt/app
    ports:
      - "30080:80"
    volumes:
      - ./:/opt/app
      - ./assets/redis-node.conf:/usr/local/etc/redis/redis-node.conf
      - ./assets/redis-standalone.conf:/usr/local/etc/redis/redis-standalone.conf
    networks:
      - redis_network
    deploy:
      mode: replicated
      replicas: 3