FROM redister:dev

COPY . /opt/app
COPY ./assets/redis-node.conf /usr/local/etc/redis/redis-node.conf
COPY ./assets/redis-standalone.conf /usr/local/etc/redis/redis-standalone.conf

WORKDIR /opt/app

CMD [ "node", "index.js", "--run-redister" ]