version: "3.6"

networks:
  redis_network:
    driver: overlay
    external: false
volumes:
  redis_data:
services:
  redis:
    image: redister:stable
    volumes:
      - redis_data:/data
    environment:
      - LOG_LEVEL=INFO
    ports:
      - "44195:80"
    networks:
      - redis_network
    deploy:
      mode: replicated
      replicas: 6