version: "3.6"

networks:
  redis_network:
    driver: overlay
    external: false

services:
  redis:
    image: redister:stable
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - LOG_LEVEL=INFO
    sysctls:
      - net.core.somaxconn=65536
    ports:
      - "44195:80"
    networks:
      - redis_network
    deploy:
      mode: replicated
      replicas: 6